version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

  nginx:
    image: nginx:stable
    restart: always
    network_mode: host
    volumes:
      - "./stack/nginx.conf:/etc/nginx/conf.d/default.conf"
    command: ["nginx", "-g", "daemon off;"]
