version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:stable
    restart: always
    network_mode: host
    volumes:
      - './stack/nginx.conf:/etc/nginx/conf.d/default.conf'
    command: ["nginx", "-g", "daemon off;"]